### ISSUE TITLE
Laravel 5.5 / 5.6 support

### ISSUE THREAD

**Issue by SergkeiM** [montross50/UptimeRobotApi#1]
Is there is a plan to support Laravel 5.5 / 5.6?

**Comment by montross50** [comment]
Yes. I wrote this library for a larger project. That project is getting upgraded next month. This will get upgraded at that time.

**Comment by montross50** [comment]
Sorry for the delay. The project I mentioned was sidelined for a short time. I have just now upgrade to support 5.6. 5.5 may work but I may have pinned the composer versions in a way that will prevent it. My use case is 5.6 so I will leave 5.5 support as a PR or cross that bridge when we get to it thing.
